In [ ]:
input = [1,3,4,5]


#  now weights for each input
weights = [
    [4,5,1,9],
    [6,4,4.7,8],
    [6.7,8,2,7]
]

#  now weights for each input
weight1 = weights[0]
weight2 = weights[1]
weight3 = weights[2]

# bias is associated to each node/neuron to the layer
bias = [1,2,0.5]

output1 = [
    input[0]*weight1[0] + bias[0]+
    input[1]*weight2[1] + bias[0]+
    input[2]*weight3[2] + bias[0]
]
output2 = [
    input[0]*weight1[0] + bias[1]+
    input[1]*weight2[1] + bias[1]+
    input[2]*weight3[2] + bias[1]
]
output3 = [
    input[0]*weight1[0] + bias[2]+
    input[1]*weight2[1] + bias[2]+
    input[2]*weight3[2] + bias[2]
]
print("output1 for neuron one ", output1)
print("output1 for neuron two ", output2)
print("output1 for neuron three ", output3)

output1 for neuron one  [27]
output1 for neuron two  [30]
output1 for neuron three  [25.5]


In [ ]:
op = []

for i in range(len(weights)): # Iterate through each neuron
    current_neuron_weights = weights[i]
    current_neuron_bias = bias[i]

    neuron_output = 0
    for j in range(len(input)): # Iterate through inputs and corresponding weights for the current neuron
        neuron_output += input[j] * current_neuron_weights[j]

    neuron_output += current_neuron_bias
    op.append(neuron_output) # Append a single output for each neuron

print(op)

[69, 78.8, 74.2]


In [ ]:
import numpy as nm

In [ ]:
nm.dot(weights,nm.array(input).T)+ bias

array([69. , 78.8, 74.2])

In [ ]:
import numpy as np


In [ ]:
ar = [[1,2,3],[3,4,5],[5,4,1]]
s = np.max(ar,axis=1,keepdims=True)


In [ ]:
ar - s

array([[-2, -1,  0],
       [-2, -1,  0],
       [ 0, -1, -4]])

In [ ]:
s

array([[3],
       [5],
       [5]])