In [2]:
import tensorflow as tf

In [3]:
daily_sails_numbers = [12,-432,234,54,100,567,77,88,98]

In [6]:
# // built the simple tf dataset from  python list
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sails_numbers)

In [11]:
for data in tf_dataset.take(2):
    print(data.numpy())


12
-432


In [21]:
for data in tf_dataset:
    print(data.numpy())

12
-432
234
54
100
567
77
88
98


In [36]:
for data in tf_dataset.batch(3):
    print(data.numpy())

[  12 -432  234]
[ 54 100 567]
[77 88 98]
